initialization
initializeDigitizersUsageIds
	DigitizersUsageIds := {
	16r0 -> #'Undefined'.
	16r1 -> #'Digitizer'.
	16r2 -> #'Pen'.
	16r3 -> #'Light Pen'.
	16r4 -> #'Touch Screen'.
	16r5 -> #'Touch Pad'.
	16r6 -> #'White Board'.
	16r7 -> #'Coordinate Measuring Machine'.
	16r8 -> #'3-D Digitizer'.
	16r9 -> #'Stereo Plotter'.
	16rA -> #'Articulated Arm'.
	16rB -> #'Armature'.
	16rC -> #'Multiple Point Digitizer'.
	16rD -> #'Free Space Wand'.
	16r20 -> #'Stylus'.
	16r21 -> #'Puck'.
	16r22 -> #'Finger'.
	16r30 -> #'Tip Pressure'.
	16r31 -> #'Barrel Pressure'.
	16r32 -> #'In Range'.
	16r33 -> #'Touch'.
	16r34 -> #'Untouch'.
	16r35 -> #'Tap'.
	16r36 -> #'Quality'.
	16r37 -> #'Data Valid'.
	16r38 -> #'Transducer Index'.
	16r39 -> #'Tablet Function Keys'.
	16r3A -> #'Program Change Keys'.
	16r3B -> #'Battery Strength'.
	16r3C -> #'Invert'.
	16r3D -> #'X Tilt'.
	16r3E -> #'Y Tilt'.
	16r3F -> #'Azimuth'.
	16r40 -> #'Altitude'.
	16r41 -> #'Twist'.
	16r42 -> #'Tip Switch'.
	16r43 -> #'Secondary Tip Switch'.
	16r44 -> #'Barrel Switch'.
	16r45 -> #'Eraser'.
	16r46 -> #'Tablet Pick' } asDictionary