initialization
initializeSimulationControlsUsageIds
	SimulationControlsUsageIds := {
	16r0 -> #'Undefined'.
	16r1 -> #'Flight Simulation Device'.
	16r2 -> #'Automobile Simulation Device'.
	16r3 -> #'Tank Simulation Device'.
	16r4 -> #'Spaceship Simulation Device'.
	16r5 -> #'Submarine Simulation Device'.
	16r6 -> #'Sailing Simulation Device'.
	16r7 -> #'Motorcycle Simulation Device'.
	16r8 -> #'Sports Simulation Device'.
	16r9 -> #'Airplane Simulation Device'.
	16rA -> #'Helicopter Simulation Device'.
	16rB -> #'Magic Carpet Simulation Device'.
	16rC -> #'Bicycle'.
	16r20 -> #'Flight Control Stick'.
	16r21 -> #'Flight Stick'.
	16r22 -> #'Cyclic Control'.
	16r23 -> #'Cyclic Trim'.
	16r24 -> #'Flight Yoke'.
	16r25 -> #'Track Control'.
	16r26 -> #'Driving Control'.
	16rB0 -> #'Aileron'.
	16rB1 -> #'Aileron Trim'.
	16rB2 -> #'Anti-Torque Control'.
	16rB3 -> #'Auto-pilot enable'.
	16rB4 -> #'Chaff Release'.
	16rB5 -> #'Collective Control'.
	16rB6 -> #'Dive Brake'.
	16rB7 -> #'Electronic Counter Measures'.
	16rB8 -> #'Elevator'.
	16rB9 -> #'Elevator Trim'.
	16rBA -> #'Rudder'.
	16rBB -> #'Throttle'.
	16rBC -> #'Flight Communication'.
	16rBD -> #'Flare Release'.
	16rBE -> #'Landing Gear'.
	16rBF -> #'Toe Brake'.
	16rC0 -> #'Trigger'.
	16rC1 -> #'Weapons Arm'.
	16rC2 -> #'Weapons Select'.
	16rC3 -> #'Wing Flaps'.
	16rC4 -> #'Accelerator'.
	16rC5 -> #'Brake'.
	16rC6 -> #'Clutch'.
	16rC7 -> #'Shifter'.
	16rC8 -> #'Steering'.
	16rC9 -> #'Turret Direction'.
	16rCA -> #'Barrel Elevation'.
	16rCB -> #'Dive Plane'.
	16rCC -> #'Ballast'.
	16rCD -> #'Bicycle Crank'.
	16rCE -> #'Handle Bars'.
	16rCF -> #'Front Brake'.
	16rD0 -> #'Rear Brake' } asDictionary