initialization
initializeMonitorUsageIds
	MonitorUsageIds := {
	16r0 -> #'Undefined'.
	16r1 -> #'Monitor Control'.
	16r2 -> #'EDID Information'.
	16r3 -> #'VDIF Information'.
	16r4 -> #'VESA Version'.
	16r5 -> #'On Screen Display'.
	16r6 -> #'Auto Size Center'.
	16r7 -> #'Polarity Horz Synch'.
	16r8 -> #'Polarity Vert Synch'.
	16r9 -> #'Sync Type'.
	16rA -> #'Screen Position'.
	16rB -> #'Horizontal Frequency'.
	16rC -> #'Vertical Frequency' } asDictionary