initialization
initializeGamingControlsUsageIds
	GamingControlsUsageIds := {
	16r0 -> #'Undefined'.
	16r1 -> #'3D Game Controller'.
	16r2 -> #'Pinball Device'.
	16r3 -> #'Gun Device'.
	16r20 -> #'Point of View'.
	16r21 -> #'Turn Right/Left'.
	16r22 -> #'Pitch Right/Left'.
	16r23 -> #'Roll Forward/Backward'.
	16r24 -> #'Move Right/Left'.
	16r25 -> #'Move Forward/Backward'.
	16r26 -> #'Move Up/Down'.
	16r27 -> #'Lean Right/Left'.
	16r28 -> #'Lean Forward/Backward'.
	16r29 -> #'Height of POV'.
	16r2A -> #'Flipper'.
	16r2B -> #'Secondary Flipper'.
	16r2C -> #'Bump'.
	16r2D -> #'New Game'.
	16r2E -> #'Shoot Ball'.
	16r2F -> #'Player'.
	16r30 -> #'Gun Bolt'.
	16r31 -> #'Gun Clip'.
	16r32 -> #'Gun Selector'.
	16r33 -> #'Gun Single Shot'.
	16r34 -> #'Gun Burst'.
	16r35 -> #'Gun Automatic'.
	16r36 -> #'Gun Safety'.
	(16r37 to: 16rFFFF) -> #'reserved' } asDictionary