initialization
initializeTelephonyDevicesUsageIds
	TelephonyDevicesUsageIds := {
	16r0 -> #'Unassigned'.
	16r1 -> #'Phone'.
	16r2 -> #'Answering Machine'.
	16r3 -> #'Message Controls'.
	16r4 -> #'Handset'.
	16r5 -> #'Headset'.
	16r6 -> #'Telephony Key Pad'.
	16r7 -> #'Programmable Button'.
	16r20 -> #'Hook Switch'.
	16r21 -> #'Flash'.
	16r22 -> #'Feature'.
	16r23 -> #'Hold'.
	16r24 -> #'Redial'.
	16r25 -> #'Transfer'.
	16r26 -> #'Drop'.
	16r27 -> #'Park'.
	16r28 -> #'Forward Calls'.
	16r29 -> #'Alternate Function'.
	16r2A -> #'Line'.
	16r2B -> #'Speaker Phone'.
	16r2C -> #'Conference'.
	16r2D -> #'Ring Enable'.
	16r2E -> #'Ring Select'.
	16r2F -> #'Phone Mute'.
	16r30 -> #'Caller ID'.
	16r50 -> #'Speed Dial'.
	16r51 -> #'Store Number'.
	16r52 -> #'Recall Number'.
	16r53 -> #'Phone Directory'.
	16r70 -> #'Voice Mail'.
	16r71 -> #'Screen Calls'.
	16r72 -> #'Do Not Disturb'.
	16r73 -> #'Message'.
	16r74 -> #'Answer On/Off'.
	16r90 -> #'Inside Dial Tone'.
	16r91 -> #'Outside Dial Tone'.
	16r92 -> #'Inside Ring Tone'.
	16r93 -> #'Outside Ring Tone'.
	16r94 -> #'Priority Ring Tone'.
	16r95 -> #'Inside Ringback'.
	16r96 -> #'Priority Ringback'.
	16r97 -> #'Line Busy Tone'.
	16r98 -> #'Reorder Tone'.
	16r99 -> #'Call Waiting Tone'.
	16r9A -> #'Confirmation Tone 1'.
	16r9B -> #'Confirmation Tone 2'.
	16r9C -> #'Tones Off'.
	16rB0 -> #'Phone Key 0'.
	16rB1 -> #'Phone Key 1'.
	16rB2 -> #'Phone Key 2'.
	16rB3 -> #'Phone Key 3'.
	16rB4 -> #'Phone Key 4'.
	16rB5 -> #'Phone Key 5'.
	16rB6 -> #'Phone Key 6'.
	16rB7 -> #'Phone Key 7'.
	16rB8 -> #'Phone Key 8'.
	16rB9 -> #'Phone Key 9'.
	16rBA -> #'Phone Key Star'.
	16rBB -> #'Phone Key Pound'.
	16rBC -> #'Phone Key A'.
	16rBD -> #'Phone Key B'.
	16rBE -> #'Phone Key C'.
	16rBF -> #'Phone Key D' } asDictionary