initialization
initializeSportsControlsUsageIds
	SportsControlsUsageIds := {
	16r0 -> #'Unidentified'.
	16r1 -> #'Baseball Bat'.
	16r2 -> #'Golf Club'.
	16r3 -> #'Rowing Machine'.
	16r4 -> #'Treadmill'.
	16r30 -> #'Oar'.
	16r31 -> #'Slope'.
	16r32 -> #'Rate'.
	16r33 -> #'Stick Speed'.
	16r34 -> #'Stick Face Angle'.
	16r35 -> #'Stick Heel/Toe'.
	16r36 -> #'Stick Follow Through'.
	16r37 -> #'Stick Tempo'.
	16r38 -> #'Stick Type'.
	16r39 -> #'Stick Height'.
	16r50 -> #'Putter'.
	16r51 -> #'1 Iron'.
	16r52 -> #'2 Iron'.
	16r53 -> #'3 Iron'.
	16r54 -> #'4 Iron'.
	16r55 -> #'5 Iron'.
	16r56 -> #'6 Iron'.
	16r57 -> #'7 Iron'.
	16r58 -> #'8 Iron'.
	16r59 -> #'9 Iron'.
	16r5A -> #'10 Iron'.
	16r5B -> #'11 Iron'.
	16r5C -> #'Sand Wedge'.
	16r5D -> #'Loft Wedge'.
	16r5E -> #'Power Wedge'.
	16r5F -> #'1 Wood'.
	16r60 -> #'3 Wood'.
	16r61 -> #'5 Wood'.
	16r62 -> #'7 Wood'.
	16r63 -> #'9 Wood'.
	(16r64 to: 16rFFFF) -> #'reserved' } asDictionary