initialization
initializeGenericDesktopControlsUsageIds
	GenericDesktopUsageIds := {
	16r0 -> #'Undefined'.
	16r1 -> #'Pointer'.
	16r2 -> #'Mouse'.
	16r4 -> #'Joystick'.
	16r5 -> #'Game Pad'.
	16r6 -> #'Keyboard'.
	16r7 -> #'Keypad'.
	16r30 -> #'X'.
	16r31 -> #'Y'.
	16r32 -> #'Z'.
	16r33 -> #'Rx'.
	16r34 -> #'Ry'.
	16r35 -> #'Rz'.
	16r36 -> #'Slider'.
	16r37 -> #'Dial'.
	16r38 -> #'Wheel'.
	16r39 -> #'Hat switch'.
	16r3A -> #'Counted Buffer'.
	16r3B -> #'Byte Count'.
	16r3C -> #'Motion Wakeup'.
	16r40 -> #'Vx'.
	16r41 -> #'Vy'.
	16r42 -> #'Vz'.
	16r43 -> #'Vbrx'.
	16r44 -> #'Vbry'.
	16r45 -> #'Vbrx'.
	16r46 -> #'Vno'.
	16r80 -> #'System Control'.
	16r81 -> #'System Power Down'.
	16r82 -> #'System Sleep'.
	16r83 -> #'System Wake Up'.
	16r84 -> #'System Context Menu'.
	16r85 -> #'System Main Menu'.
	16r86 -> #'System App Menu'.
	16r87 -> #'System Help Menu'.
	16r88 -> #'System Menu Exit'.
	16r89 -> #'System Menu Select'.
	16r8A -> #'System Menu Right'.
	16r8B -> #'System Menu Left'.
	16r8C -> #'System Menu Up'.
	16r8D -> #'System Menu Down' } asDictionary