initialization
initializeLEDsUsageIds
	LEDsUsageIds := {
	16r0 -> #'Undefined'.
	16r1 -> #'Num Lock'.
	16r2 -> #'Caps Lock'.
	16r3 -> #'Scroll Lock'.
	16r4 -> #'Compose'.
	16r5 -> #'Kana'.
	16r6 -> #'Power'.
	16r7 -> #'Shift'.
	16r8 -> #'Do Not Disturb'.
	16r9 -> #'Mute'.
	16rA -> #'Tone Enable'.
	16rB -> #'High Cut Filter'.
	16rC -> #'Low Cut Filter'.
	16rD -> #'Equalizer Enable'.
	16rE -> #'Sound Field On'.
	16rF -> #'Surround field On'.
	16r10 -> #'Repeat'.
	16r11 -> #'Stereo'.
	16r12 -> #'Sampling Rate Detect'.
	16r13 -> #'Spinning'.
	16r14 -> #'CAV'.
	16r15 -> #'CLV'.
	16r16 -> #'Recording Format Detect'.
	16r17 -> #'Off-Hook'.
	16r18 -> #'Ring'.
	16r19 -> #'Message Waiting'.
	16r1A -> #'Data Mode'.
	16r1B -> #'Battery Operation'.
	16r1C -> #'Battery OK'.
	16r1D -> #'Battery Low'.
	16r1E -> #'Speaker'.
	16r1F -> #'Head Set'.
	16r20 -> #'Hold'.
	16r21 -> #'Microphone'.
	16r22 -> #'Coverage'.
	16r23 -> #'Night Mode'.
	16r24 -> #'Send Calls'.
	16r25 -> #'Call Pickup'.
	16r26 -> #'Conference'.
	16r27 -> #'Stand-by'.
	16r28 -> #'Camera On'.
	16r29 -> #'Camera Off'.
	16r2A -> #'On-Line'.
	16r2B -> #'Off-Line'.
	16r2C -> #'Busy'.
	16r2D -> #'Ready'.
	16r2E -> #'Paper-Out'.
	16r2F -> #'Paper-Jam'.
	16r30 -> #'Remote'.
	16r31 -> #'Forward'.
	16r32 -> #'Reverse'.
	16r33 -> #'Stop'.
	16r34 -> #'Rewind'.
	16r35 -> #'Fast Forward'.
	16r36 -> #'Play'.
	16r37 -> #'Pause'.
	16r38 -> #'Record'.
	16r39 -> #'Error'.
	16r3A -> #'Usage Selected Indicator'.
	16r3B -> #'Usage In Use Indicator'.
	16r3C -> #'Usage Multi Mode Indicator'.
	16r3D -> #'Indicator On'.
	16r3E -> #'Indicator Flash'.
	16r3F -> #'Indicator Slow Blink'.
	16r40 -> #'Indicator Fast Blink'.
	16r41 -> #'Indicator Off'.
	16r42 -> #'Flash On Time'.
	16r43 -> #'Slow Blink On Time'.
	16r44 -> #'Slow Blink Off Time'.
	16r45 -> #'Fast Blink On Time'.
	16r46 -> #'Fast Blink Off Time'.
	16r47 -> #'Usage Indicator Color'.
	16r48 -> #'Red'.
	16r49 -> #'Green'.
	16r4A -> #'Amber'.
	16r4B -> #'Generic Indicator' } asDictionary