initialization
initializeConsumerDevicesUsageIds
	ConsumerDevicesUsageIds := {
	16r0 -> #'Unassigned'.
	16r1 -> #'Consumer Control'.
	16r2 -> #'Numeric Key Pad'.
	16r20 -> #'+10'.
	16r21 -> #'+100'.
	16r22 -> #'AM/PM'.
	16r30 -> #'Power'.
	16r31 -> #'Reset'.
	16r32 -> #'Sleep'.
	16r33 -> #'Sleep After'.
	16r34 -> #'Sleep Mode'.
	16r35 -> #'Illumination'.
	16r36 -> #'Function Buttons'.
	16r40 -> #'Menu'.
	16r41 -> #'Menu  Pick'.
	16r42 -> #'Menu Up'.
	16r43 -> #'Menu Down'.
	16r44 -> #'Menu Left'.
	16r45 -> #'Menu Right'.
	16r46 -> #'Menu Escape'.
	16r47 -> #'Menu Value Increase'.
	16r48 -> #'Menu Value Decrease'.
	16r60 -> #'Data On Screen'.
	16r61 -> #'Closed Caption'.
	16r62 -> #'Closed Caption Select'.
	16r63 -> #'VCR/TV'.
	16r64 -> #'Broadcast Mode'.
	16r65 -> #'Snapshot'.
	16r66 -> #'Still'.
	16r80 -> #'Selection'.
	16r81 -> #'Assign Selection'.
	16r82 -> #'Mode Step'.
	16r83 -> #'Recall Last'.
	16r84 -> #'Enter Channel'.
	16r85 -> #'Order Movie'.
	16r86 -> #'Channel'.
	16r87 -> #'Media Selection'.
	16r88 -> #'Media Select Computer'.
	16r89 -> #'Media Select TV'.
	16r8A -> #'Media Select WWW'.
	16r8B -> #'Media Select DVD'.
	16r8C -> #'Media Select Telephone'.
	16r8D -> #'Media Select Program Guide'.
	16r8E -> #'Media Select Video Phone'.
	16r8F -> #'Media Select Games'.
	16r90 -> #'Media Select Messages'.
	16r91 -> #'Media Select CD'.
	16r92 -> #'Media Select VCR'.
	16r93 -> #'Media Select Tuner'.
	16r94 -> #'Quit'.
	16r95 -> #'Help'.
	16r96 -> #'Media Select Tape'.
	16r97 -> #'Media Select Cable'.
	16r98 -> #'Media Select Satellite'.
	16r99 -> #'Media Select Security'.
	16r9A -> #'Media Select Home'.
	16r9B -> #'Media Select Call'.
	16r9C -> #'Channel Increment'.
	16r9D -> #'Channel Decrement'.
	16rA0 -> #'VCR Plus'.
	16rA1 -> #'Once'.
	16rA2 -> #'Daily'.
	16rA3 -> #'Weekly'.
	16rA4 -> #'Monthly'.
	16rB0 -> #'Play'.
	16rB1 -> #'Pause'.
	16rB2 -> #'Record'.
	16rB3 -> #'Fast Forward'.
	16rB4 -> #'Rewind'.
	16rB5 -> #'Scan Next Track'.
	16rB6 -> #'Scan Previous Track'.
	16rB7 -> #'Stop'.
	16rB8 -> #'Eject'.
	16rB9 -> #'Random Play'.
	16rBA -> #'Select Disc'.
	16rBB -> #'Enter Disc'.
	16rBC -> #'Repeat'.
	16rBD -> #'Tracking'.
	16rBE -> #'Track Normal'.
	16rBF -> #'Slow Tracking'.
	16rC0 -> #'Frame Forward'.
	16rC1 -> #'Frame Back'.
	16rC2 -> #'Mark'.
	16rC3 -> #'Clear Mark'.
	16rC4 -> #'Repeat From Mark'.
	16rC5 -> #'Return To Mark'.
	16rC6 -> #'Search Mark Forward'.
	16rC7 -> #'Search Mark Backwards'.
	16rC8 -> #'Counter Reset'.
	16rC9 -> #'Show Counter'.
	16rCA -> #'Tracking Increment'.
	16rCB -> #'Tracking Decrement'.
	16rE0 -> #'Volume'.
	16rE1 -> #'Balance'.
	16rE2 -> #'Mute'.
	16rE3 -> #'Bass'.
	16rE4 -> #'Treble'.
	16rE5 -> #'Bass Boost'.
	16rE6 -> #'Surround Mode'.
	16rE7 -> #'Loudness'.
	16rE8 -> #'MPX'.
	16rE9 -> #'Volume Up'.
	16rEA -> #'Volume Down'.
	16rF0 -> #'Speed Select'.
	16rF1 -> #'Playback Speed'.
	16rF2 -> #'Standard Play'.
	16rF3 -> #'Long Play'.
	16rF4 -> #'Extended Play'.
	16rF5 -> #'Slow'.
	16r100 -> #'Fan Enable'.
	16r101 -> #'Fan Speed'.
	16r102 -> #'Light'.
	16r103 -> #'Light Illumination Level'.
	16r104 -> #'Climate Control Enable'.
	16r105 -> #'Room Temperature'.
	16r106 -> #'Security Enable'.
	16r107 -> #'Fire Alarm'.
	16r108 -> #'Police Alarm' } asDictionary