initialization
initializeAlphanumericDisplayUsageIds
	AlphanumericDisplayUsageIds := { 
	16r0 -> #'Undefined'.
	16r1 -> #'Alphanumeric Display'.
	16r20 -> #'Display Attributes Report'.
	16r21 -> #'ASCII Character Set'.
	16r22 -> #'Data Read Back'.
	16r23 -> #'Font Read Back'.
	16r24 -> #'Display Control Report'.
	16r25 -> #'Clear Display'.
	16r26 -> #'Display Enable'.
	16r27 -> #'Screen Saver Delay'.
	16r28 -> #'Screen Saver Enable'.
	16r29 -> #'Vertical Scroll'.
	16r2A -> #'Horizontal Scroll'.
	16r2B -> #'Character Report'.
	16r2C -> #'Display Data'.
	16r2D -> #'Display Status'.
	16r2E -> #'Stat Not Ready'.
	16r2F -> #'Stat Ready'.
	16r30 -> #'Err Not a loadable character'.
	16r31 -> #'Err Font data cannot be read'.
	16r32 -> #'Cursor Position Report'.
	16r33 -> #'Row'.
	16r34 -> #'Column'.
	16r35 -> #'Rows'.
	16r36 -> #'Columns'.
	16r37 -> #'Cursor Pixel Positioning'.
	16r38 -> #'Cursor Mode'.
	16r39 -> #'Cursor Enable'.
	16r3A -> #'Cursor Blink'.
	16r3B -> #'Font Report'.
	16r3C -> #'Font Data'.
	16r3D -> #'Character Width'.
	16r3E -> #'Character Height'.
	16r3F -> #'Character Spacing Horizontal'.
	16r40 -> #'Character Spacing Vertical'.
	16r41 -> #'Unicode Character Set' } asDictionary