SystemOrganization addCategory: #HumanInterfaceDevice!
SystemOrganization addCategory: 'HumanInterfaceDevice-Backends'!
SystemOrganization addCategory: 'HumanInterfaceDevice-Codes'!
SystemOrganization addCategory: 'HumanInterfaceDevice-Errors'!
SystemOrganization addCategory: 'HumanInterfaceDevice-Items'!
SystemOrganization addCategory: 'HumanInterfaceDevice-Objects'!
SystemOrganization addCategory: 'HumanInterfaceDevice-Parser'!
SystemOrganization addCategory: 'HumanInterfaceDevice-Traits'!
